title: Weightlessness space game
hero_image: images/banner.png
description: Learn how to simulate the effects of weightlessness in space with this Scratch game
original_url: https://raspberrypi.org/learning/weightlessness
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: Set the space scene
- title: Add weightlessness
- title: Control direction
- title: Catch a sprite 
- title: Make a game of it with variables 
- title: Create a Game Over screen 
- title: What next? 

