title: Weightlessness Space Game
hero_image: images/banner.png
description: Learn how to simulate the effects of weightlessness in space with this
Scratch game
original_url: https://raspberrypi.org/learning/weightlessness
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: true
<<<<<<< HEAD
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
=======
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: space, games
technologies: scratch
site_areas: ''
steps:
>>>>>>> master
- title: Introduction
- title: What you will need
- title: 'Weightlessness: Mooncake in Space'
- title: Set the stage with a space theme
- title: Setting the start position
- title: Adding movement
- title: Adding directonal movement
- title: Wrapping space
- title: Make a game of it with variables
- title: Catch the randomly moving ISS
- title: Creating a Game Over screen
- title: What next?